language: c++

matrix:
  include:

    - os: linux
      env: BUILD_TYPE="vanilla"
           CMAKE_OPTIONS="-D CMAKE_BUILD_TYPE=Release -DCMAKE_RULE_MESSAGES=OFF -DCMAKE_VERBOSE_MAKEFILE=ON"
           CTEST_OPTIONS="-V"
           MAKEFLAGS="--no-print-directory"
      script:
        - ./.ci/docker/script/docker-run bassosimone/mk-debian:testing cmake
      services:
        - docker
      sudo: required

    - os: linux
      env: BUILD_TYPE="asan"
           CFLAGS="-fsanitize=address"
           CXXFLAGS="-fsanitize=address"
           LDFLAGS="-fsanitize=address"
           CMAKE_OPTIONS="-D CMAKE_BUILD_TYPE=Debug -DCMAKE_RULE_MESSAGES=OFF -DCMAKE_VERBOSE_MAKEFILE=ON"
           CTEST_OPTIONS="-V"
           MAKEFLAGS="--no-print-directory"
      script:
        - ./.ci/docker/script/docker-run bassosimone/mk-debian:testing cmake
      services:
        - docker
      sudo: required

    - os: linux
      env: BUILD_TYPE="lsan"
           CFLAGS="-fsanitize=leak"
           CXXFLAGS="-fsanitize=leak"
           LDFLAGS="-fsanitize=leak"
           CMAKE_OPTIONS="-D CMAKE_BUILD_TYPE=Debug -DCMAKE_RULE_MESSAGES=OFF -DCMAKE_VERBOSE_MAKEFILE=ON"
           CTEST_OPTIONS="-V"
           MAKEFLAGS="--no-print-directory"
      script:
        - ./.ci/docker/script/docker-run bassosimone/mk-debian:testing cmake
      services:
        - docker
      sudo: required

    - os: linux
      env: BUILD_TYPE="ubsan"
           CFLAGS="-fsanitize=undefined -fno-sanitize-recover"
           CXXFLAGS="-fsanitize=undefined -fno-sanitize-recover"
           LDFLAGS="-fsanitize=undefined"
           CMAKE_OPTIONS="-D CMAKE_BUILD_TYPE=Release -DCMAKE_RULE_MESSAGES=OFF -DCMAKE_VERBOSE_MAKEFILE=ON"
           CTEST_OPTIONS="-V"
           MAKEFLAGS="--no-print-directory"
      script:
        - ./.ci/docker/script/docker-run bassosimone/mk-debian:testing cmake
      services:
        - docker
      sudo: required

    - os: linux
      env: BUILD_TYPE="vanilla"
           CMAKE_OPTIONS="-D CMAKE_BUILD_TYPE=Release -DCMAKE_RULE_MESSAGES=OFF -DCMAKE_VERBOSE_MAKEFILE=ON"
           CTEST_OPTIONS="-V"
           CXXFLAGS="-stdlib=libc++"
           MAKEFLAGS="--no-print-directory"
           MK_CC=clang
           MK_CXX=clang++
      script:
        - ./.ci/docker/script/docker-run bassosimone/mk-debian:testing cmake
      services:
        - docker
      sudo: required

    - os: linux
      env: BUILD_TYPE="coverage"
           CFLAGS="-O0 -g -fprofile-arcs -ftest-coverage"
           CMAKE_OPTIONS="-D CMAKE_BUILD_TYPE=Debug -DCMAKE_RULE_MESSAGES=OFF -DCMAKE_VERBOSE_MAKEFILE=ON"
           COVERALLS_OPTIONS="--include client.cpp --include libndt.cpp --include libndt.hpp"
           CTEST_OPTIONS="-V"
           CXXFLAGS="-O0 -g -fprofile-arcs -ftest-coverage"
           LDFLAGS="-lgcov"
           MAKEFLAGS="--no-print-directory"
      script:
        - ./.ci/docker/script/docker-run bassosimone/mk-debian:testing cmake
      services:
        - docker
      sudo: required
