image: Visual Studio 2017

environment:
  matrix:
    - GENERATOR: "Visual Studio 15 2017"
    - GENERATOR: "Visual Studio 15 2017 Win64"

build_script:
  - cmd: cmake "-G%GENERATOR%" -DCMAKE_BUILD_TYPE=Release .
  - cmd: cmake --build . -- /nologo
  - cmd: ctest -V -C Release -a -j8
