image: Visual Studio 2017

environment:
  matrix:
    - platform: x86
      GENERATOR: "Visual Studio 15 2017"
    - platform: x64
      GENERATOR: "Visual Studio 15 2017 Win64"


install:
  - cmd: set PATH=%PATH%;%PYTHON%/Scripts/
  - cmd: pip.exe install conan

build_script:
  - cmd: conan install .
  - cmd: cmake "-G%GENERATOR%" -DCMAKE_BUILD_TYPE=Release .
  - cmd: cmake --build . -- /nologo
  - cmd: ctest -V -C Release -a -j8
